<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container16yAYcw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container16yAYcw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container16yAYcw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container16yAYcw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container16yAYcw\App_KernelDevDebugContainer([
    'container.build_hash' => '16yAYcw',
    'container.build_id' => '62c3c015',
    'container.build_time' => 1591731213,
], __DIR__.\DIRECTORY_SEPARATOR.'Container16yAYcw');
