<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVExGbDX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVExGbDX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVExGbDX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVExGbDX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVExGbDX\App_KernelDevDebugContainer([
    'container.build_hash' => 'VExGbDX',
    'container.build_id' => '91262b44',
    'container.build_time' => 1592335019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVExGbDX');
